CREATE TABLE IF NOT EXISTS m4_todos (
    id SERIAL PRIMARY KEY,
    task VARCHAR(128) NOT NULL,
    due DATE NOT NULL DEFAULT CURRENT_DATE,
    assigned VARCHAR(60) NOT NULL DEFAULT 'self',
    is_complete BOOLEAN NOT NULL DEFAULT FALSE,
    completed TIMESTAMP DEFAULT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (task, due)
);